import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {listenAuth, loginWithGoogle, logoutGoogle} from './firebase';
import {categories, productsSeed, promosSeed, faqSeed, company, menuTree} from './data';
import {Search, Filter, Bell, ShoppingCart, UserCircle, LogOut, Bot, Menu, X, ChevronDown, Heart, Eye, Zap, Star, MapPin, Download, CreditCard, Wallet, Gift, Trophy, Megaphone, LayoutDashboard, PackagePlus, Users, Store, ShieldCheck, BarChart3, MessageCircle, Mail, Headphones, BriefcaseBusiness, Settings, Plus, Trash2, Edit, Upload, FileText, KeyRound, Clock3, CheckCircle2, AlertTriangle, Send, Paperclip, Smile, MoreVertical, Pin, Copy, Archive, RefreshCw, Moon, Sun} from 'lucide-react';
import './styles.css';

const rp=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
const ls=(k,v)=>{try{return JSON.parse(localStorage.getItem(k))||v}catch{return v}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const today=()=>new Date().toLocaleString('id-ID',{dateStyle:'medium', timeStyle:'short'});

function App(){
 const [user,setUser]=useState(null), [page,setPage]=useState('home'), [drawer,setDrawer]=useState(false), [profile,setProfile]=useState(false), [contact,setContact]=useState(false), [detail,setDetail]=useState(null), [dark,setDark]=useState(false);
 const [q,setQ]=useState(''), [filterOpen,setFilterOpen]=useState(false), [category,setCategory]=useState('Semua'), [sort,setSort]=useState('Terbaru');
 const [products,setProducts]=useState(()=>ls('mm_products_v40',productsSeed)), [cart,setCart]=useState(()=>ls('mm_cart_v40',[])), [promoIndex,setPromoIndex]=useState(0);
 const [coins,setCoins]=useState(()=>ls('mm_coins_v40',250)), [wishlist,setWishlist]=useState(()=>ls('mm_wishlist_v40',[])), [downloads,setDownloads]=useState(()=>ls('mm_downloads_v40',[])), [licenses,setLicenses]=useState(()=>ls('mm_licenses_v40',[]));
 useEffect(()=>listenAuth(setUser),[]);
 useEffect(()=>{const t=setInterval(()=>setPromoIndex(x=>(x+1)%promosSeed.length),4500);return()=>clearInterval(t)},[]);
 useEffect(()=>save('mm_cart_v40',cart),[cart]); useEffect(()=>save('mm_coins_v40',coins),[coins]); useEffect(()=>save('mm_wishlist_v40',wishlist),[wishlist]); useEffect(()=>save('mm_downloads_v40',downloads),[downloads]); useEffect(()=>save('mm_licenses_v40',licenses),[licenses]); useEffect(()=>save('mm_products_v40',products),[products]);
 const filtered=useMemo(()=>{let arr=products.filter(p=>(category==='Semua'||p.category===category)&&(`${p.name} ${p.desc} ${p.seller} ${p.city}`.toLowerCase().includes(q.toLowerCase()))); if(sort==='Harga Termurah')arr.sort((a,b)=>a.price-b.price); if(sort==='Harga Termahal')arr.sort((a,b)=>b.price-a.price); if(sort==='Rating Tertinggi')arr.sort((a,b)=>b.rating-a.rating); if(sort==='A-Z')arr.sort((a,b)=>a.name.localeCompare(b.name)); return arr},[products,category,q,sort]);
 const total=cart.reduce((s,i)=>s+i.price*i.qty,0);
 const addCart=p=>setCart(c=>{const f=c.find(x=>x.id===p.id); return f?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]});
 const buyNow=p=>{addCart(p); setPage('checkout')};
 const checkout=()=>{const bought=cart.map(i=>({id:i.id,name:i.name,category:i.category,date:today(),file:`${i.name.replaceAll(' ','-')}.zip`,status:'Aktif'})); setDownloads([...bought,...downloads]); setLicenses([...cart.filter(i=>i.category==='Software').map(i=>({product:i.name,key:`MM-${Math.random().toString(36).slice(2,10).toUpperCase()}-${Date.now().toString().slice(-4)}`,status:'Aktif',date:today()})),...licenses]); setCoins(coins+Math.floor(total/10000)); setCart([]); setPage('success')};
 return <div className={dark?'app dark':'app'}>
  <Header user={user} login={loginWithGoogle} logout={logoutGoogle} q={q} setQ={setQ} cart={cart} setPage={setPage} setDrawer={setDrawer} setProfile={setProfile} setFilterOpen={setFilterOpen} dark={dark} setDark={setDark}/>
  {drawer&&<SideMenu close={()=>setDrawer(false)} setPage={setPage}/>} {profile&&<ProfileMenu user={user} login={loginWithGoogle} logout={logoutGoogle} close={()=>setProfile(false)} setPage={setPage}/>} {filterOpen&&<FilterPanel sort={sort} setSort={setSort} category={category} setCategory={setCategory} close={()=>setFilterOpen(false)}/>} 
  {page==='home'&&<Home promo={promosSeed[promoIndex]} promoIndex={promoIndex} setPromoIndex={setPromoIndex} products={filtered} addCart={addCart} buyNow={buyNow} openDetail={setDetail} wishlist={wishlist} setWishlist={setWishlist} setPage={setPage}/>} 
  {page==='checkout'&&<Checkout cart={cart} setCart={setCart} total={total} checkout={checkout} setPage={setPage}/>} {page==='success'&&<Success setPage={setPage}/>} {page==='buyer'&&<BuyerDashboard coins={coins} setCoins={setCoins} downloads={downloads} licenses={licenses} wishlist={wishlist} products={products} setPage={setPage}/>} {page==='seller'&&<SellerDashboard products={products} setProducts={setProducts}/>} {page==='operator'&&<OperatorDashboard products={products} setProducts={setProducts}/>} {page==='faq'&&<InfoPage title='Pusat Bantuan' items={faqSeed}/>} {page==='blog'&&<Blog/>} {page==='coins'&&<Coins coins={coins} setCoins={setCoins}/>} {page==='contact'&&<ContactCenter/>}
  {detail&&<ProductDetail p={detail} close={()=>setDetail(null)} addCart={addCart} buyNow={buyNow}/>} <button className='float-ai' onClick={()=>setContact(true)}><Bot/> </button>{contact&&<ContactCenter floating close={()=>setContact(false)}/>}<Ticker/>
 </div>
}
function Header({user,login,logout,q,setQ,cart,setPage,setDrawer,setProfile,setFilterOpen,dark,setDark}){return <header className='topbar'><button className='iconBtn' onClick={()=>setDrawer(true)}><Menu/></button><div className='hello'><b>Selamat Datang, {user?.displayName?.split(' ')[0]||'Guest'}</b><small>{company.tagline}</small></div><div className='searchBox'><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder='Cari produk, seller, FAQ, artikel...'/><button className='flatIcon' onClick={()=>setFilterOpen(true)}><Filter/></button></div><button className='flatIcon' onClick={()=>setPage('checkout')}><ShoppingCart/><em>{cart.length}</em></button><button className='flatIcon'><Bell/></button><button className='flatIcon' onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button><button className='profileBtn' onClick={()=>setProfile(true)}>{user?.photoURL?<img src={user.photoURL}/>:<UserCircle/>}</button></header>}
function SideMenu({close,setPage}){const [open,setOpen]=useState('Software'); return <aside className='drawer'><div className='drawerHead'><b>Madhayana Menu</b><button onClick={close}><X/></button></div>{menuTree.map(m=><div className='menuGroup' key={m.title}><button onClick={()=>m.items.length?setOpen(open===m.title?'':m.title):(setPage(m.title==='Home'?'home':m.title==='Contact'?'contact':'home'),close())}><span>{m.icon} {m.title}</span>{m.items.length>0&&<ChevronDown/>}</button>{open===m.title&&m.items.map(i=><button className='sub' key={i}>{i}</button>)}{open===m.title&&m.items.length>0&&<button className='addMenu'><Plus/> Tambah {m.title}</button>}</div>)}<div className='drawerActions'><button onClick={()=>{setPage('buyer');close()}}>Buyer Center</button><button onClick={()=>{setPage('seller');close()}}>Seller Center</button><button onClick={()=>{setPage('operator');close()}}>Operator Center</button></div></aside>}
function ProfileMenu({user,login,logout,close,setPage}){return <div className='profileMenu'><div className='profileTop'>{user?.photoURL?<img src={user.photoURL}/>:<UserCircle/>}<b>{user?.displayName||'Guest Mode'}</b><small>{user?.email||'Belum login'}</small></div>{['Profil','Pengaturan','Tambahkan Akun','Switch Akun','Tentang Aplikasi'].map(x=><button key={x}>{x}</button>)}<button onClick={()=>{setPage('buyer');close()}}>Dashboard Buyer</button><button onClick={()=>{setPage('seller');close()}}>Dashboard Seller</button><button onClick={()=>{setPage('operator');close()}}>Operator</button>{user?<button onClick={logout}><LogOut/> Keluar</button>:<button onClick={login}>Masuk dengan Google</button>}</div>}
function FilterPanel({sort,setSort,category,setCategory,close}){return <div className='filterPanel'><b>Filter Pencarian</b><label>Urutkan<select value={sort} onChange={e=>setSort(e.target.value)}>{['Terbaru','A-Z','Harga Termurah','Harga Termahal','Rating Tertinggi','Paling Banyak Terjual','Paling Banyak Dilihat'].map(x=><option key={x}>{x}</option>)}</select></label><label>Kategori<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><div className='filterTags'>{['Ready','Promo','Verified','Star+','Official','5 Bintang','Tangerang','Jakarta','Online'].map(x=><span key={x}>{x}</span>)}</div><button onClick={close}>Terapkan Filter</button></div>}
function Home({promo,promoIndex,setPromoIndex,products,addCart,buyNow,openDetail,wishlist,setWishlist,setPage}){return <main className='home'><section className='hero'><div className='highlight'><span>{promo.badge}</span><h1>{promo.title}</h1><p>{promo.sub}</p><button onClick={()=>setPage(promo.target)}><Zap/> {promo.cta}</button><div className='dots'>{promosSeed.map((_,i)=><button key={i} className={i===promoIndex?'on':''} onClick={()=>setPromoIndex(i)}/>)}</div></div><div className='widgets'><Widget title='Cuaca' value='28°C' icon='🌤️'/><Widget title='Kurs' value='USD 16K' icon='💱'/><Widget title='Notifikasi' value='12 Baru' icon='🔔'/><div className='mediaWidget'>▶ Video Promo</div></div></section><section className='quickCats'>{categories.slice(1).map(c=><button key={c}>{c}</button>)}</section><Section title='Produk Populer'><div className='productGrid'>{products.map(p=><ProductCard key={p.id} p={p} addCart={addCart} buyNow={buyNow} openDetail={openDetail} wishlist={wishlist} setWishlist={setWishlist}/>)}</div></Section><Section title='Rekomendasi AI'><div className='aiBox'><Bot/> Produk dipilih berdasarkan minat user, kategori populer, rating, dan riwayat aktivitas.</div></Section><Section title='Seller Terbaik'><div className='sellerRow'>{['Madhayana Official','Madhayana Studio','Madhayana Academy'].map(s=><div className='sellerCard' key={s}><Store/><b>{s}</b><small>Rating 4.9 · SLA cepat</small><button>Follow</button></div>)}</div></Section></main>}
function Widget(p){return <div className='widget'><span>{p.icon}</span><small>{p.title}</small><b>{p.value}</b></div>}
function Section({title,children}){return <section className='section'><h2>{title}</h2>{children}</section>}
function ProductCard({p,addCart,buyNow,openDetail,wishlist,setWishlist}){const liked=wishlist.includes(p.id); return <article className='productCard'><div className='imgWrap' onClick={()=>openDetail(p)}><img src={p.image}/><span className='badge'>{p.badge}</span></div><div className='prodBody'><h3 onClick={()=>openDetail(p)}>{p.name}</h3><div><del>{rp(p.oldPrice)}</del><strong>{rp(p.price)}</strong></div><p><Star/> {p.rating} · {p.sold} terjual · <Eye/> {p.views}</p><small><MapPin/> {p.city} · {p.seller}</small><div className='actionIcons'><button onClick={()=>setWishlist(liked?wishlist.filter(x=>x!==p.id):[...wishlist,p.id])} title='Favorit'><Heart fill={liked?'currentColor':'none'}/></button><button onClick={()=>addCart(p)} title='Keranjang'><ShoppingCart/></button><button onClick={()=>buyNow(p)} title='Beli cepat'><Zap/></button><button onClick={()=>openDetail(p)} title='Detail'><Eye/></button></div></div></article>}
function ProductDetail({p,close,addCart,buyNow}){return <div className='modal'><div className='detail'><button className='close' onClick={close}><X/></button><div className='detailGrid'><div><img className='detailImg' src={p.image}/><div className='thumbs'><img src={p.image}/><div>🎥 Demo</div><div>📄 Brosur</div></div></div><div><span className='badge'>{p.badge}</span><h1>{p.name}</h1><p className='rating'><Star/> {p.rating} · {p.sold} terjual · {p.views} dilihat</p><h2>{rp(p.price)}</h2><p>{p.desc}</p><div className='detailActions'><button onClick={()=>addCart(p)}><ShoppingCart/> Keranjang</button><button className='primary' onClick={()=>buyNow(p)}><Zap/> Beli Sekarang</button></div></div></div><div className='tabs'><button>Deskripsi</button><button>Spesifikasi</button><button>Yang Didapat</button><button>FAQ</button><button>Ulasan</button></div><div className='specGrid'>{Object.entries(p.specs||{}).map(([k,v])=><><b>{k}</b><span>{v}</span></>)}</div><ul className='includes'>{(p.includes||[]).map(x=><li key={x}><CheckCircle2/> {x}</li>)}</ul></div></div>}
function Checkout({cart,setCart,total,checkout,setPage}){return <main className='page split'><section><h1>Keranjang & Checkout</h1>{cart.length===0&&<p>Keranjang masih kosong.</p>}{cart.map(i=><div className='cartLine' key={i.id}><img src={i.image}/><div><b>{i.name}</b><small>{i.category} · {i.seller}</small></div><b>{rp(i.price)}</b><span>x{i.qty}</span><button onClick={()=>setCart(cart.filter(x=>x.id!==i.id))}><Trash2/></button></div>)}</section><aside className='summary'><h2>Ringkasan</h2><p>Subtotal <b>{rp(total)}</b></p><p>Biaya layanan <b>{rp(cart.length?1000:0)}</b></p><p>Bonus koin <b>{Math.floor(total/10000)} koin</b></p><hr/><h2>{rp(total+(cart.length?1000:0))}</h2><div className='payOptions'><button>DANA Placeholder</button><button>QRIS Placeholder</button><button>Midtrans Placeholder</button></div><button className='primary wide' disabled={!cart.length} onClick={checkout}><CreditCard/> Bayar Sekarang</button><small>Setelah payment gateway aktif, tombol ini akan memanggil DANA/Midtrans dan menerima callback otomatis.</small></aside></main>}
function Success({setPage}){return <main className='page success'><CheckCircle2/><h1>Pembayaran Berhasil</h1><p>Produk digital otomatis masuk ke Pusat Unduhan dan lisensi software masuk ke Pusat Lisensi.</p><button onClick={()=>setPage('buyer')}>Buka Dashboard Buyer</button></main>}
function BuyerDashboard({coins,setCoins,downloads,licenses,wishlist,products,setPage}){return <Dashboard title='Buyer Center' menu={['Pesanan','Pembayaran','Pusat Unduhan','Pusat Lisensi','Wishlist','Voucher','Koin','Membership','Referral']}><div className='cards'><Stat icon={<Wallet/>} label='Koin' value={coins}/><Stat icon={<Gift/>} label='Voucher' value='5 Aktif'/><Stat icon={<Download/>} label='Unduhan' value={downloads.length}/><Stat icon={<Trophy/>} label='Membership' value='Bronze'/></div><CoinsMini coins={coins} setCoins={setCoins}/><h2>Pusat Unduhan</h2>{downloads.map(d=><div className='listItem' key={d.id+d.date}><Download/><b>{d.name}</b><span>{d.date}</span><button>Download</button></div>)}<h2>Pusat Lisensi</h2>{licenses.map(l=><div className='listItem' key={l.key}><KeyRound/><b>{l.product}</b><code>{l.key}</code><span>{l.status}</span></div>)}<h2>Wishlist</h2><div className='miniProducts'>{products.filter(p=>wishlist.includes(p.id)).map(p=><button onClick={()=>setPage('home')} key={p.id}>{p.name}</button>)}</div></Dashboard>}
function CoinsMini({coins,setCoins}){return <div className='checkin'><h2>Daily Check-In</h2>{[10,20,30,40,50,75,100].map((n,i)=><button key={n} onClick={()=>setCoins(coins+n)}>Hari {i+1}<b>+{n}</b></button>)}<button className='primary' onClick={()=>setCoins(coins+1000)}>Top Up 1.000 Koin</button></div>}
function Coins({coins,setCoins}){return <main className='page'><h1>Koin Madhayana</h1><CoinsMini coins={coins} setCoins={setCoins}/></main>}
function SellerDashboard({products,setProducts}){return <Dashboard title='Seller Center' menu={['Beranda','Pesanan','Produk','Chat','Ulasan','Pendapatan','Analitik','Promosi','Pusat File','Pengaturan Toko']}><div className='cards'><Stat icon={<CreditCard/>} label='Pendapatan' value='Rp5,2 Jt'/><Stat icon={<PackagePlus/>} label='Produk' value={products.length}/><Stat icon={<MessageCircle/>} label='Chat Baru' value='7'/><Stat icon={<Star/>} label='Rating' value='4.9'/></div><h2>Produk Seller</h2><button className='primary'><Plus/> Tambah Produk</button>{products.map(p=><div className='listItem' key={p.id}><img src={p.image}/><b>{p.name}</b><span>{rp(p.price)}</span><button><Edit/></button><button><Trash2/></button></div>)}</Dashboard>}
function OperatorDashboard({products,setProducts}){return <Dashboard title='Operator Center' menu={['Dashboard','User','Seller','Produk','Menu Website','Banner & Widget','Chatbot','CS','Sales','Email','Pembayaran','Refund','Tiket','Moderasi','Statistik','Broadcast','Log','Sistem']}><div className='cards'><Stat icon={<Users/>} label='User' value='15.250'/><Stat icon={<Store/>} label='Seller' value='350'/><Stat icon={<CreditCard/>} label='Transaksi' value='Rp125 Jt'/><Stat icon={<ShieldCheck/>} label='SLA' value='98%'/></div><h2>Manajemen Produk</h2><button className='primary'><Plus/> Tambah Produk</button>{products.map(p=><div className='listItem' key={p.id}><img src={p.image}/><b>{p.name}</b><span>{p.category}</span><button><Edit/></button><button><Trash2/></button></div>)}<h2>Kontrol Sistem</h2><div className='opTiles'><button><Megaphone/> Broadcast</button><button><Upload/> Banner</button><button><Bot/> Prompt AI</button><button><BarChart3/> Statistik</button></div></Dashboard>}
function Dashboard({title,menu,children}){return <main className='dashboard'><aside>{menu.map(m=><button key={m}>{m}</button>)}</aside><section><h1>{title}</h1>{children}</section></main>}
function Stat({icon,label,value}){return <div className='stat'>{icon}<small>{label}</small><b>{value}</b></div>}
function ContactCenter({floating,close}){const [tab,setTab]=useState('Chat Bot'); const [msgs,setMsgs]=useState([{from:'bot',text:'Halo, ada yang bisa kami bantu?',time:today()}]); const [txt,setTxt]=useState(''); const send=()=>{if(!txt)return;setMsgs([...msgs,{from:'me',text:txt,time:today()},{from:'bot',text:'Pesan diterima. Tim kami akan membantu sesuai kanal yang dipilih.',time:today()}]);setTxt('')}; return <div className={floating?'contactModal':'page'}><div className='contactCenter'><aside>{['Chat Bot','Customer Service','Sales','Email'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t==='Chat Bot'?<Bot/>:t==='Customer Service'?<Headphones/>:t==='Sales'?<BriefcaseBusiness/>:<Mail/>}{t}<small>{t==='Chat Bot'?'AI otomatis':t==='Email'?'Tiket resmi':'SLA 05:00'}</small></button>)}</aside><section><div className='chatHead'><b>{tab}</b><span className={tab==='Chat Bot'?'status green':'status red'}>{tab==='Chat Bot'?'Online':'Baru Terkirim'}</span><button><MoreVertical/></button>{close&&<button onClick={close}><X/></button>}</div>{tab==='Email'?<EmailBox/>:<><div className='messages'>{msgs.map((m,i)=><div className={m.from==='me'?'msg me':'msg'} key={i}><p>{m.text}</p><small>{m.time}</small></div>)}</div><div className='quick'><button>Cek Pesanan</button><button>Cek Pembayaran</button><button>FAQ</button></div><div className='composer'><button><Paperclip/></button><button><Smile/></button><input value={txt} onChange={e=>setTxt(e.target.value)} placeholder='Tulis pesan...'/><button onClick={send}><Send/></button></div></>}</section></div></div>}
function EmailBox(){return <div className='emailBox'><div className='emailList'><button>Kotak Masuk</button><button>Terkirim</button><button>Draft</button><button>Arsip</button></div><div className='emailForm'><input placeholder='Kepada'/><input placeholder='Subjek'/><textarea placeholder='Tulis email resmi di sini...'/><button><Paperclip/> Lampiran</button><button className='primary'><Send/> Kirim Email</button></div></div>}
function InfoPage({title,items}){return <main className='page'><h1>{title}</h1>{items.map(i=><div className='faq' key={i.id}><b>{i.q}</b><p>{i.a}</p></div>)}</main>}
function Blog(){return <main className='page'><h1>Blog & SEO</h1>{['Tips memilih software bisnis','Cara memulai toko digital','Panduan sertifikasi online'].map(x=><div className='faq' key={x}><b>{x}</b><p>Artikel SEO untuk mendukung traffic organik Madhayana Market.</p></div>)}</main>}
function Ticker(){return <div className='ticker'><b>{new Date().toLocaleTimeString('id-ID')}</b><marquee>Promo software hari ini · Check-in harian dapat koin · DANA/Midtrans menyusul setelah approval · CS dan Sales memakai SLA</marquee></div>}

createRoot(document.getElementById('root')).render(<App/>);
